apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-service-account
  namespace: email-wallet-v11
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: email-wallet-v11
  name: deployment-restart-role
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-restart-rolebinding
  namespace: email-wallet-v11
subjects:
  - kind: ServiceAccount
    name: cronjob-service-account
    namespace: email-wallet-v11
roleRef:
  kind: Role
  name: deployment-restart-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-deployment
  namespace: email-wallet-v11
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cronjob-service-account
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  kubectl rollout restart deployment relayer -n email-wallet-v11
          restartPolicy: OnFailure
